### PR TITLE
more choice of multiple handler

### PR DESCRIPTION
**Pull request by Blackjack200**

### CODE REVIEW

**Comment by Sandertv** [comment]
What do you think about adding your project and Peex to https://github.com/Thunder33345/awesome-dragonfly and pointing to that instead? That way we don't have to keep updating this.

**Comment by Thunder33345** [comment]
some opinions on the library: 
https://github.com/Blackjack200/dfevents/blob/master/mhandler/handler.go#L12
if you are using `map[any]any` as a set it should been `map[any]struct{}`

since you are storing the handlers as a map, the call order of the handler will be random
this should be emphasized on the docs, as developers might beexpecting handler's order will be the order they are registered in

**Comment by Blackjack200** [comment]
> What do you think about adding your project and Peex to https://github.com/Thunder33345/awesome-dragonfly and pointing to that instead? That way we don't have to keep updating this.

thanks

**Comment by Blackjack200** [comment]
> some opinions on the library: https://github.com/Blackjack200/dfevents/blob/master/mhandler/handler.go#L12 if you are using `map[any]any` as a set it should been `map[any]struct{}`
> 
> since you are storing the handlers as a map, the call order of the handler will be random this should be emphasized on the docs, as developers might beexpecting handler's order will be the order they are registered in

thanks for review

**Pull request closed without merging**
